version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000:8000"
    volumes:
      - static_data:/static

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - flask
    volumes:
      - static_data:/freshcraft/static

volumes:
  static_data:
