version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
    depends_on:
      - flask
